### ISSUE TITLE
默认defaultExecuteTimeout 60秒在网络差的环境下不够用

### ISSUE THREAD

**Issue by soooldier** [storyicon/powerproto#4]
https://github.com/storyicon/powerproto/blob/7b2c0762d4cacb428328236b3b097cce7b9af4f1/pkg/component/pluginmanager/manager.go#L31

建议executeTimeout可以通过传入参数控制

**Comment by storyicon** [comment]
Sorry I'm late, I was delayed by some things some time ago, I have supported this feature via https://github.com/storyicon/powerproto/pull/6: 
1. I have adjusted the default timeout for subcommands to `5min`.
2. you can now control the timeout of subcommands with the -t parameter, for example `-t 60s`, or `-t 10m`.
If it doesn't meet your expectation, please feel free to contact me.

**Comment by storyicon** [comment]
Thanks for your suggestion!

**Comment by soooldier** [comment]
棒极了～感谢感谢
